name: Deploy BOT non prod
on:
  push:
    branches:
      - main

jobs:
  run-it:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: BartlomiejSzczotka
          repo: triggered_repo
          github_token: ${{ secrets.triger_my }}
          workflow_file_name: run-it-test.yaml
          ref: main
#          client_payload: '{"inputs.app": "STOCK_HOLD_ORCHESTRATOR"}'